server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: yxw660786
  redis:
    timeout: 10000ms
    host: localhost
    port: 6379
    database: 0
#    database可以选择使用哪个库
#    lettuce.pool设置连接池相关的配置
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    #    消息失败回调
    publisher-returns: true
#    消息确认回调
    publisher-confirm-type: correlated
mybatis-plus:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
    - classpath:mapper/*mapper.xml
  type-aliases-package: com.example.server.pojo
  configuration:
#    取消驼峰命名
    map-underscore-to-camel-case: false
logging:
  level:
    com.example.server.mapper: debug

jwt:
  tokenHeader: Authorization
  secret: yeb-secret
#  过期时间:60*60*24*7
  expiration: 604800
  tokenHead: Bearer

